server:
  port: 8091
  servlet:
    context-path: /rabbit-api/

spring:

  rabbitmq:
    addresses: localhost:5672
    password: password
    username: root

  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
           
  kafka:
    listener:
      ack-mode: MANUAL_IMMEDIATE
    bootstrap-servers:
    - localhost:9091
    - localhost:9092
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: false
      group-id: rabbit-api
      properties:
        "[spring.json.trusted.packages]": "*" 
        "[spring.json.type.mapping]": > 
          br.com.marcelodsp.kafkateste.documents.Funcionario:br.com.marcelodsp.rabbitteste.entity.Funcionario,
          br.com.marcelodsp.kafkateste.documents.Empresa:br.com.marcelodsp.rabbitteste.entity.Empresa
---
my-config:
  
  rabbit:
    exchange-name: exchange.testes
    queue-name: queue.testes
    
  kafka:
    topic-name: topic.testes
    
    
 
    